version: "3.9"
services:
  redis:
    image: redis:7-alpine3.20
    container_name: redis_dev
    ports:
      - "6379:6379"
    command: ["redis-server"]
    networks:
      - dev-network
  mysql:
    image: mysql:8
    container_name: mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: myapp
    ports:
      - "3306:3306"
    networks:
      - dev-network
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
networks:
  dev-network:
