app:
  name: rocket-hexagonal
  port: 7000
  debug:
    config: false
  fiber:
    enable_print_routes: true
    enable_splitting_on_parsers: true
  cache:
    redis:
      addr: localhost:6379
      username:
      password:
      db: 0
  datastore:
    mysql:
      host: localhost
      port: 3306
      username: myapp
      password: myapp
      db: myapp
